<?php
/**
 * PureScan AI Scanner - Handles AI analysis via OpenRouter
 *
 * @package PureScan\AI
 * @since 1.1.026
 */
namespace PureScan\AI;

use PureScan\AI_Client;
use WP_Error;

if (!defined('ABSPATH')) {
    exit;
}

require_once PURESCAN_DIR . 'includes/ai-client.php';

/**
 * Class AI_Scanner
 *
 * Handles manual AI code scanning via AJAX.
 */
class AI_Scanner {
    
    /**
     * AJAX: Force AI analysis on a file from scan results
     * Final version: Exact error repeating + no badge change on error + no alert
     * Updated: Manual file reading with internal/external path resolution for external files
     */
    public static function force_ai_analysis() {
        check_ajax_referer( PURESCAN_NONCE, 'nonce' );
    
        if ( ! current_user_can( 'manage_options' ) ) {
            wp_send_json_error( [ 'message' => 'Permission denied' ] );
        }
    
        // phpcs:ignore WordPress.Security.NonceVerification.Missing, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Nonce verified at top; raw prompt required for AI analysis.
        $prompt = wp_unslash( $_POST['prompt'] ?? '' );
    
        // phpcs:ignore WordPress.Security.NonceVerification.Missing -- Nonce verified at top.
        $path = sanitize_text_field( wp_unslash( $_POST['path'] ?? '' ) );
    
        if (empty($path)) {
            wp_send_json_error(['message' => 'Missing file path']);
        }
    
        $client = new \PureScan\AI_Client();
    
        if (!$client->is_connected()) {
            wp_send_json_error(['message' => 'OpenRouter API is not configured or connected']);
        }
    
        // If prompt is empty (manual "Analyze with AI" from results), read the file manually
        // with proper internal/external path resolution to support external files
        if (empty($prompt)) {
            // First attempt: internal path (inside WordPress root)
            $internal_path = ABSPATH . ltrim($path, '/');
            $real_path     = realpath($internal_path);
    
            // Second attempt: external path (from server root)
            if (!$real_path || !is_file($real_path) || !is_readable($real_path)) {
                $external_path = '/' . ltrim($path, '/');
                $real_path     = realpath($external_path);
            }
    
            // Final check
            if (!$real_path || !is_file($real_path) || !is_readable($real_path)) {
                wp_send_json_error(['message' => 'The file could not be accessed.']);
            }
    
            $code = @file_get_contents($real_path);
            if ($code === false) {
                wp_send_json_error(['message' => 'Failed to read file content.']);
            }
    
            // Pass the raw code to AI_Client (it will build the prompt internally)
            $response = $client->analyze_code($code, $path);
        } else {
            // Custom prompt provided (e.g., from AI Scan tab)
            $response = $client->analyze_code($prompt, $path);
        }
    
        /* =============================================================
         * 1. WP_Error → return the EXACT real error from OpenRouter
         * ============================================================= */
        if (is_wp_error($response)) {
            wp_send_json_error([
                'message' => $response->get_error_message()
            ]);
        }
    
        /* =============================================================
         * 2. Empty or invalid response
         * ============================================================= */
        if (!is_string($response) || trim($response) === '') {
            wp_send_json_error([
                'message' => 'AI returned an empty or invalid response.'
            ]);
        }
    
        /* =============================================================
         * 3. Parse AI response
         * ============================================================= */
        $parsed = \PureScan\Scan\Scan_Engine::parse_structured_ai_response($response);
        $raw_status = trim($parsed['status'] ?? '');
        $status = strtolower($raw_status);
    
        /* =============================================================
         * 4. Invalid status → show warning, do NOT change badge
         * ============================================================= */
        if (!in_array($status, ['clean', 'suspicious', 'malicious'], true)) {
            
            $ai_debug = [
                'prompt_sent' => $prompt ?: '(auto-generated by AI_Client)',
                'raw_response' => $response,
                'parsed_status' => 'failed',
                'model' => $client->get_current_model(),
                'timestamp' => current_time('mysql'),
                'retry_possible' => true,
                'error' => 'AI did not return a valid status (expected: CLEAN, SUSPICIOUS, or MALICIOUS)',
                'force_retry' => true,
            ];
    
            $permanent_results = get_option('purescan_ai_results', []);
            $permanent_results[$path] = $ai_debug;
            update_option('purescan_ai_results', $permanent_results, false);
    
            $html = '<div class="purescan-ai-details purescan-ai-failed" style="margin:16px 0 0;padding:16px;background:#fffbeb;border-radius:8px;font-size:14px;line-height:1.7;color:#92400e;">
                        <strong>Warning: AI Analysis Unclear or Failed</strong><br><br>
                        The AI model did not provide a clear verdict (CLEAN, SUSPICIOUS, or MALICIOUS).<br>
                        The previous file status has been preserved.<br>
                        You can try analyzing again.
                     </div>';
    
            wp_send_json_success([
                'html' => $html,
                'new_status' => null, // Prevents badge update
                'message' => 'AI analysis was unclear'
            ]);
        }
    
        /* =============================================================
         * 5. Valid AI response → success
         * ============================================================= */
        $status = in_array($status, ['clean', 'suspicious'], true) ? $status : 'malicious';
    
        $ai_debug = [
            'prompt_sent' => $prompt ?: '(auto-generated by AI_Client)',
            'raw_response' => $response,
            'parsed_status' => $status,
            'model' => $client->get_current_model(),
            'timestamp' => current_time('mysql'),
            'retry_possible' => false,
            'error' => null,
            'force_retry' => false,
        ];
    
        // Save result permanently
        $permanent_results = get_option('purescan_ai_results', []);
        $permanent_results[$path] = $ai_debug;
        update_option('purescan_ai_results', $permanent_results, false);
        
        // Save result quarantine
        $quarantine_ai_results = get_option('purescan_quarantine_ai_results', []);
        $quarantine_ai_results[$path] = $ai_debug;
        update_option('purescan_quarantine_ai_results', $quarantine_ai_results, false);
    
        // Update live scan state if exists
        $state = get_option(PURESCAN_STATE, []);
        if (!empty($state['findings'])) {
            foreach ($state['findings'] as &$finding) {
                if (($finding['path'] ?? '') === $path) {
                    foreach ($finding['snippets'] as &$snippet) {
                        $snippet['ai_status'] = $status;
                        $snippet['ai_analysis'] = $parsed['analysis'] ?? $response;
                        $snippet['without_ai'] = false;
                        $snippet['ai_debug'] = $ai_debug;
                    }
                    unset($snippet);
                    break;
                }
            }
            unset($finding);
            update_option(PURESCAN_STATE, $state, false);
        }
    
        // Clean explanation text
        $explanation = $parsed['analysis'] ?? $response;
        $explanation = preg_replace('/^(Details|Explanation|Analysis|Reasoning|Summary)\s*[:：]\s*/i', '', $explanation);
        $explanation = trim($explanation);
    
        $ai_status = strtoupper($status);
        $class = $ai_status === 'CLEAN' ? 'purescan-ai-clean' :
                 ($ai_status === 'SUSPICIOUS' ? 'purescan-ai-suspicious' : 'purescan-ai-malicious');
    
        $html = '<div class="purescan-ai-details ' . $class . '" style="border-left-color: ' .
                ($ai_status === 'MALICIOUS' ? '#ef4444' : ($ai_status === 'CLEAN' ? '#10b981' : '#f59e0b')) . ';">
                    ' . wp_kses_post(nl2br(esc_html($explanation))) . '
                 </div>';
    
        wp_send_json_success([
            'html' => $html,
            'new_status' => $ai_status,
            'message' => 'AI analysis completed successfully'
        ]);
    }

    /**
     * AJAX handler: Scan code manually via AI (from AI Scan tab or modal)
     *
     * @return void
     */
    public static function scan_file_via_ai() {
        try {
            check_ajax_referer(PURESCAN_NONCE, 'nonce');
    
            if (!current_user_can('manage_options')) {
                wp_send_json_error(__('Unauthorized access.', 'purescan'));
            }
    
            $code     = self::get_sanitized_code();
            $filepath = self::get_sanitized_filepath();
    
            if ($code === '') {
                wp_send_json_error(__('Please enter some code to scan.', 'purescan'));
            }
    
            $client = new AI_Client();
            if (!$client->is_connected()) {
                wp_send_json_error(__('OpenRouter API is not configured. Please check settings.', 'purescan'));
            }
    
            $result = $client->analyze_code($code, $filepath);
    
            if (is_wp_error($result)) {
                wp_send_json_error(__('AI analysis failed: ', 'purescan') . $result->get_error_message());
            }
    
            if (empty($result) || !is_string($result)) {
                wp_send_json_error(__('AI returned an empty response.', 'purescan'));
            }
    
            // Detect overall status
            $is_malicious = self::detect_malicious_state($result);
    
            // Get short summary
            $summary = self::get_summary($result);
    
            // Format full analysis + remove unwanted prefixes like "Details:", "Analysis:", etc.
            $analysis = self::format_analysis_output($result);
            $analysis = preg_replace('/^(Details|Explanation|Analysis|Reasoning|Summary)\s*[:：]\s*/i', '', $analysis);
            $analysis = trim($analysis);
    
            wp_send_json_success([
                'analysis'     => $analysis,
                'summary'      => $summary,
                'is_malicious' => $is_malicious, // 'clean' | 'suspicious' | 'malicious'
            ]);
    
        } catch (\Throwable $e) {
            wp_send_json_error(__('An unexpected error occurred. Please try again.', 'purescan'));
        }
    }

    private static function get_sanitized_code(): string {
        // phpcs:ignore WordPress.Security.NonceVerification.Missing -- Nonce already verified in the main AJAX handler.
        if ( ! isset( $_POST['code'] ) ) {
            return '';
        }
    
        // phpcs:ignore WordPress.Security.NonceVerification.Missing, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Nonce verified in handler; raw code required for AI analysis (cannot sanitize further without breaking content).
        $code = wp_unslash( $_POST['code'] );
    
        $code = preg_replace( '/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/', '', $code );
        $code = trim( $code );
        if ( strlen( $code ) > 500 * 1024 ) {
            $code = substr( $code, 0, 500 * 1024 ) . "\n\n[Truncated: Code too large for analysis]";
        }
        return $code;
    }

    private static function get_sanitized_filepath(): string {
        // phpcs:ignore WordPress.Security.NonceVerification.Missing -- Nonce already verified in the main AJAX handler.
        if ( empty( $_POST['filepath'] ) ) {
            return 'manual_input.php';
        }
    
        // phpcs:ignore WordPress.Security.NonceVerification.Missing, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Nonce verified in handler; raw filepath needed before sanitization.
        $filepath = wp_unslash( $_POST['filepath'] );
    
        if ( ! is_string( $filepath ) ) {
            return 'manual_input.php';
        }
        $filepath = sanitize_file_name( $filepath );
        $filepath = str_replace( [ '..', '\\' ], [ '', '/' ], $filepath );
        $filepath = ltrim( $filepath, '/' );
        return $filepath ?: 'manual_input.php';
    }

    /**
     * Detect malicious state: clean, suspicious, or malicious.
     *
     * @param string $text AI response
     * @return string 'clean' | 'suspicious' | 'malicious'
     */
    private static function detect_malicious_state(string $text): string {
        $text = strtoupper($text);
        if (preg_match('/Status:\s*MALICIOUS/i', $text)) {
            return 'malicious';
        }
        if (preg_match('/Status:\s*SUSPICIOUS/i', $text)) {
            return 'suspicious';
        }
        if (preg_match('/Status:\s*CLEAN/i', $text)) {
            return 'clean';
        }
        return self::detect_malicious_state_fallback(strtolower($text));
    }
    
    private static function detect_malicious_state_fallback(string $text): string {
        $danger_keywords = ['malware', 'backdoor', 'webshell', 'eval', 'base64_decode', 'obfuscated'];
        $safe_keywords = ['clean', 'safe', 'no malware', 'legitimate', 'benign'];
        $danger_count = 0;
        $safe_count = 0;
        foreach ($danger_keywords as $word) if (strpos($text, $word) !== false) $danger_count++;
        foreach ($safe_keywords as $word) if (strpos($text, $word) !== false) $safe_count++;
        if ($danger_count > $safe_count + 1) return 'malicious';
        if ($danger_count > 0 && $safe_count > 0) return 'suspicious';
        return 'clean';
    }

    /**
     * Extract a short summary from AI response.
     *
     * @param string $text
     * @return string
     */
    private static function get_summary(string $text): string {
        $lines = array_filter(array_map('trim', explode("\n", $text)));
        $first = $lines[0] ?? '';

        if (strlen($first) > 8 && strlen($first) < 200) {
            return $first;
        }

        return __('Analysis complete.', 'purescan');
    }

    /**
     * Format full AI analysis for safe HTML output.
     *
     * @param string $text
     * @return string
     */
    private static function format_analysis_output(string $text): string {
        $lines = explode("\n", $text);
        $lines = array_map(function ($line) {
            return preg_replace('/^\s+/', '', $line);
        }, $lines);
        $text = implode("\n", $lines);
    
        $text = wp_strip_all_tags($text);
        $text = esc_html($text);
    
        $allowed = [
            'br'     => [],
            'code'   => [],
            'strong' => [],
            'em'     => [],
            'p'      => [],
            'ul'     => [],
            'ol'     => [],
            'li'     => [],
        ];
    
        return wp_kses($text, $allowed);
    }
    
    public static function non_ai_scan_code() {
        check_ajax_referer(PURESCAN_NONCE, 'nonce');
    
        if (!current_user_can('manage_options')) {
            wp_send_json_error(['message' => 'Unauthorized.']);
        }
    
        if (!isset($_POST['code'])) {
            wp_send_json_error(['message' => 'No code provided.']);
        }
        
        // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash -- Raw user-provided code is required for accurate scanning; dangerous control characters are removed below.    
        $code = wp_unslash($_POST['code']);
        $code = preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/', '', $code);
        $code = trim($code);
    
        if ($code === '') {
            wp_send_json_error(['message' => 'Please enter some code to scan.']);
        }
    
        $scan_config = ['max_read_mb' => 500];
    
        $snippets = \PureScan\Scan\Scan_Engine::scan_content_standalone($code, $scan_config);
        
        $patterns_source = get_option('purescan_patterns_source', 'Local Patterns');
    
        $dangerous_lines = [];
        foreach ($snippets as $snippet) {
            foreach ($snippet['snippet_lines'] ?? [] as $sl) {
                if (!empty($sl['dangerous'])) {
                    $dangerous_lines[$sl['line']] = true;
                }
            }
        }
    
        $has_threats = !empty($dangerous_lines);
    
        $original_size = strlen($code);
        $max_display = 10 * 1024 * 1024;
        $truncated_for_display = false;
        $display_code = $code;
    
        if ($original_size > $max_display) {
            $display_code = substr($code, 0, $max_display) . "\n\n{{===[ PureScan: Code too large – only first " . size_format($max_display) . " displayed for browser performance ]===}}\n\n";
            $truncated_for_display = true;
        }
    
        $lines = explode("\n", $display_code);
    
        $display_filename = 'Pasted Code (Manual Input)';
        $filesize = size_format($original_size);
        $size_note = $truncated_for_display ? " (displaying first " . size_format($max_display) . " only)" : '';
    
        ob_start();
        ?>
        <style>
            .purescan-local-viewer-simple {margin:20px 0;background:#fff;border:1px solid #d0d7de;border-radius:12px;overflow:hidden;box-shadow:0 4px 12px rgba(0,0,0,.05);}
            .purescan-local-notice {margin:0;padding:20px 30px;border-bottom:1px solid #e1e4e8;font-size:15px;background:#f9f9f9;}
            .purescan-local-notice.clean {background:#f0fdf4;border-bottom-color:#10b981;color:#065f46;}
            .purescan-local-notice.clean strong {color:#047857;}
            .purescan-local-notice.threat {background:#ffebe9;border-bottom-color:#cf222e;color:#991b1b;}
            .purescan-local-notice.threat strong {color:#cf222e;}
            .purescan-local-info {margin:10px 30px;font-size:14px;color:#555;}
            table.purescan-local-viewer {width:100%;border-collapse:collapse;table-layout:fixed;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:14.2px;border-top: 1px solid #e1e4e8;}
            col.line-num {width:70px;}
            col.code {width:calc(100% - 70px);}
            code {background:none;}
            td.line-num {background:#f6f8fa;color:#656d76;text-align:right;padding:6px 16px 6px 0 !important;font-size:13px;user-select:none;border-right:1px solid #e1e4e8;}
            td.code {padding:6px 20px !important;word-break:break-all;font-size:14px;line-height:1.5;}
            td.code code {white-space: pre-wrap !important;}
            tr.danger {background:#ffebe9 !important;}
            tr.danger td.line-num {background:#ffebe9 !important;color:#cf222e;font-weight:600;border-left:4px solid #cf222e;}
            tr.danger td.code {background:#ffebe9 !important;}
            tr:hover td.code {background:rgba(175,184,193,0.08);}
            @media (max-width:720px) {
                td.line-num {width:55px !important;padding:6px 10px 6px 0 !important;}
                td.code {padding:6px 12px !important;font-size:13.5px;}
            }
        </style>

        <h3 class="purescan-section-title">Non-AI Scan Result (Scanned using <?php echo esc_html($patterns_source); ?>)</h3>
    
        <div class="purescan-local-viewer-simple">
            <?php if ($has_threats): ?>
                <div class="purescan-local-notice threat">
                    <strong>Potential Threats Detected</strong><br><br>
                    Suspicious code sections are highlighted in red below.<br>
                    Manual review is strongly recommended.
                </div>
            <?php else: ?>
                <div class="purescan-local-notice clean">
                    <strong>No Threats Found — Excellent!</strong><br><br>
                    No suspicious patterns were detected.
                </div>
            <?php endif; ?>
    
            <div class="purescan-local-info">
                <strong>File:</strong> <?php echo esc_html($display_filename); ?> •
                <strong>Size:</strong> <?php echo esc_html($filesize); ?><?php echo esc_html($size_note); ?>
                <?php if ($truncated_for_display): ?>
                    <span style="color:#92400e;font-weight:600;"> (scanned fully, but display truncated for performance)</span>
                <?php endif; ?>
            </div>
    
            <table class="purescan-local-viewer">
                <colgroup>
                    <col class="line-num">
                    <col class="code">
                </colgroup>
                <tbody>
                <?php foreach ($lines as $i => $line):
                    $line_num = $i + 1;
                    $is_danger = isset($dangerous_lines[$line_num]);
                    $row_class = $is_danger ? 'danger' : '';
                ?>
                    <tr class="<?php echo esc_attr($row_class); ?>">
                        <td class="line-num"><?php echo esc_html($line_num); ?></td>
                        <td class="code"><code><?php
                            if ('' === $line) {
                                echo '&nbsp;';
                            } else {
                                echo esc_html($line);
                            }
                        ?></code></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php
        $html = ob_get_clean();
    
        wp_send_json_success(['html' => $html]);
    }
}